### ISSUE TITLE
Dim fails on some minor modes loaded afterwards.

### ISSUE THREAD

**Issue by gujiaxi** [alezost/dim.el#4]
In my condition, I fetch minor mode names from `minor-mode-alist` (Yes, my purpose is to hide all the minor mode names from mode line). However, I find some minor modes add their names to `minor-mode-alist` after Dim definitions. Even if I use `after-init-hook`, there are also some minor mode names staying unchanged because they are added afterwards. So, how do I fetch the whole list of `minor-mode-alist`? (Load `dim` as late as possible?)

``` lisp
(defun dim-hook ()
  (mapc (lambda (mm) (dim-minor-name (car mm) "")) minor-mode-alist))
(add-hook 'after-init-hook 'dim-hook)
```

btw. Can I achieve my purpose using just `(setq 'minor-mode-alist nil)` though it is quite rechless?

Thanks,
Isaac

**Comment by alezost** [comment]
Hi, sorry I think I don't fully understand what you want to do.

> In my condition, I fetch minor mode names from minor-mode-alist (Yes, my purpose is to hide all the minor mode names from mode line).

So you want to have only `(foo-mode "")` entries in `minor-mode-alist`, right?

> However, I find some minor modes add their names to minor-mode-alist after Dim definitions.

After what dim definitions?  I don't undestand what it means.  New
elements are added to `minor-mode-alist` regularly.  I mean when some
package with minor mode is loaded, a new element is added there.  It
doesn't depend on dim at all.

For example, start "emacs -Q" and look at `C-h v minor-mode-alist`:
there is no element for `view-mode`.  Now run `M-x view-mode` in a
scratch buffer, and refresh the contents of the help buffer (with `g`) –
a new element for `view-mode` appears there.

> Even if I use after-init-hook, there are also some minor mode names staying unchanged because they are added afterwards. So, how do I fetch the whole list of minor-mode-alist? (Load dim as late as possible?)

It is impossible to fetch the whole list of `minor-mode-alist`.  As I
explained, this list is increased after a new minor mode will be loaded.

> btw. Can I achieve my purpose using just (setq 'minor-mode-alist nil) though it is quite rechless?

This is not a solution, since freshly loaded modes will be added to this
list.  As with example I shown: you set `minor-mode-alist` to nil, but
then you load view-mode, and `minor-mode-alist` is not nil anymore.

**Comment by alezost** [comment]
Returning to your last question, I think setting `minor-mode-alist` to
nil will do no harm.  So if you just want to get rid of any minor mode
name, you can achieve this with the following code:

``` elisp
(defun clear-minor-mode-alist (&rest _)
  (setq minor-mode-alist nil))

(add-hook 'after-load-functions 'clear-minor-mode-alist)
```

It will clear `minor-mode-alist` after every loaded file, so you can be
sure that the new mode names will not be added to `minor-mode-alist`
(well, they will be added, but they will be cleared immediately).

Is that what you want?

**Comment by gujiaxi** [comment]
Hi,
@alezost , I really appreciate your careful explanation. :+1: 

> Is that what you want?

Yes, exactly. Now, I know why and how and your `clear-minor-mode-alist` works like a charm.

Thanks,
Isaac

**Comment by alezost** [comment]
Great, glad to help :smile:
