### ISSUE TITLE
Is replacing minor mode with bitmap possible?

### ISSUE THREAD

**Issue by casouri** [alezost/dim.el#8]
Because Unicode seems to take some time to load(about a sec). It would be nice if I can replace minor modes with bitmap. Also if bitmap is available there would be a huge possibility in the replacement.

BTW the stable mepla shield in README is broken.

**Comment by alezost** [comment]
Sorry, I don't understand what you are asking about.  What bitmap do you mean and how can it replace a minor mode?  This sounds mysterious to me :smile:

> BTW the stable mepla shield in README is broken.

And I don't understand this as well.  What "melpa shield" is?

**Comment by casouri** [comment]
Sorry :smile: I mean bitmap pictures, is that easy to implement? 

And by the shield I mean the tags on the first line, the melpa one was broken yesterday.

**Comment by alezost** [comment]
> Sorry 😄 I mean bitmap pictures, is that easy to implement?

There is nothing to implement.  I mean, it is a usual emacs
feature and it should work right away.  You just need to put
whatever mode-line construct you want instead of a string and
that's it!  For example:

```elisp
(setq my-text-mode-name
      (propertize "text" 'display (create-image "back-arrow.xpm")))
(put 'my-text-mode-name 'risky-local-variable t) ; needed to make images work
(dim-major-name 'text-mode 'my-text-mode-name)
```

Evaluate the above code and open any buffer in `text-mode`.  You
should see the back-arrow icon (that comes with Emacs).

Or you can make your own icon if you wish, for example:

```elisp
(defvar my-smile-icon
  `(image :type xpm :ascent center :data "! XPM2
16 14 2 1
# c yellow
. c black
################
################
###..######..###
##....####....##
###..######..###
################
#######..#######
#######..#######
##.##########.##
###..######..###
####...##...####
######....######
################
################
"))

(put 'my-smile-icon 'risky-local-variable t)
(dim-major-name 'emacs-lisp-mode
                (propertize "smile" 'display my-smile-icon))
```

(this will work only if your X Window System supports XPM2, which is the case if you use GNU/Linux distro)

> And by the shield I mean the tags on the first line, the melpa one was broken yesterday.

Ah, apparently, it was some problem on MELPA.

Let me know if you have any problems or questions on what I wrote.

**Comment by casouri** [comment]
Thanks!
